### ISSUE TITLE
Training Code of the Models

### ISSUE THREAD

**Issue by devraj89** [FrancescoSaverioZuppichini/glasses#255]
Hi

The library is very cool and informative.

I am wondering are you planning to share the training script?

I had a look at your tutorial of VIT in https://github.com/FrancescoSaverioZuppichini/ViT and its wonderful.

I am wondering did you train all these models from scratch or simply transferred the weights from the pre-trained available models. I have heard training a VIT is quite challenging. Alternatively, I guess I could use the transfer_learning notebook as a boiler plate code to train it ? 

Thanks
Devraj

**Comment by FrancescoSaverioZuppichini** [comment]
Hi Devraj89, you can try the model in any way you like! For example, you can just load the model from glasses and use a code similar to ["train a classifier" from pytorch](https://towardsdatascience.com/how-to-train-an-image-classifier-in-pytorch-and-use-it-to-perform-basic-inference-on-single-images-99465a1e9bf5).

I do not train the model from scratch, since I will need a enormous amount of GPUs, I just copy the weights from other models and then I evaluate the resulting model on ImageNet :)
